// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Riadh Ben Abdelhamid

// Review-fix quality bar (user directive after nemotron run 7): a fix
// generated by RTL Review is generated RTL, and gets the SAME quality steps
// as rtl_generate output — echo-strip, embedded-TB strip + deterministic
// repair, and a LINT GATE that rejects a candidate compiling worse than the
// code it replaces. (Measured: a review fix rewrote a clean reset to
// 'q <= (DATA_W){1'b0}' and appended a _tb module; the lint stage's LLM then
// couldn't recover in 2 iterations.)

import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../src/llm/index.js", async function() {
  const actual = await vi.importActual("../src/llm/extractJSON.js");
  return { callLLM: vi.fn(), extractJSON: actual.extractJSON, addRetryHint: function(s) { return s; } };
});
vi.mock("../src/cli/index.js", function() {
  return {
    extractInfoEvidence: function() { return []; },
    attachInfoEvidence: function(t) { return t; },
    runCli: vi.fn(),
    parseCLIOutput: function(stderr) {
      const lines = String(stderr || "").split("\n").filter(function(l) { return l.indexOf("%Error") === 0; });
      return { errors: lines.map(function(l) { return { code: "SYNTAX", sev: "error", msg: l }; }), warnings: [] };
    },
    parseTestLine: function() { return null; },
    parseCoverageDat: function() { return { line: 90, branch: 80, toggle: 70 }; },
    CliBackendError: class extends Error {},
  };
});

const { rtlReviewNode } = await import("../src/pipeline/nodes/rtl_review.js");
const { callLLM } = await import("../src/llm/index.js");
const { runCli } = await import("../src/cli/index.js");

const CLEAN = [
  "`timescale 1ns/1ps",
  "module ctr(input logic clk, input logic rst_n, input logic en, output logic [3:0] q);",
  "  always_ff @(posedge clk or negedge rst_n) begin",
  "    if (!rst_n) q <= '0;",
  "    else if (en) q <= q + 1'b1;",
  "  end",
  "endmodule",
].join("\n");

// The measured run-7 degradation: malformed replication. The deterministic
// paren-replication transform repairs THIS form, so to test the lint gate we
// use a regression the transforms cannot fix (an unclosed begin).
const LINT_REGRESSION = CLEAN.replace("q <= q + 1'b1;", "q <= q + 1'b1; begin");

function state(cfg) {
  return {
    elicit: { modName: "ctr" },
    spec: { modName: "ctr", requirements: [], iface: [], params: [] },
    architect: { strategy: "single" },
    rtl_generate: { code: CLEAN },
    _config: Object.assign({
      provider: "openai", model: "gpt-4o", apiKey: "sk-test",
      maxRtlReviewIters: 2, syntaxRepair: true,
      backendUrl: "http://localhost:3001", strictCli: false,
      cliRetryCount: 0, backendTimeoutSec: 10, stageSettings: {},
    }, cfg || {}),
    _onLog: null, _signal: null,
    // no _services → legacy inline path (chain unavailable)
  };
}

const llmReply = (json) => ({
  text: JSON.stringify(json), tokensIn: 10, tokensOut: 5, latencyMs: 1,
  model: "gpt-4o", provider: "openai", stopReason: "stop",
});
const NEEDS_FIX = { verdict: "NEEDS_FIX", score: 40, issues: [
  { id: "RR-001", severity: "major", category: "correctness", line: 4, description: "x", fix: "y" },
] };
const PASS = { verdict: "PASS", score: 90, issues: [] };

// runCli mock: lint result depends on the candidate's content.
function lintByContent(url, payload) {
  const code = Object.values(payload.files)[0];
  const bad = code.indexOf("1'b1; begin") >= 0;   // the injected unclosed begin
  return Promise.resolve({ stdout: "", stderr: bad ? "%Error: syntax error, unexpected end\n" : "", exitCode: bad ? 1 : 0 });
}

beforeEach(() => { callLLM.mockReset(); runCli.mockReset(); });

describe("review-fix lint gate (legacy inline path)", () => {
  it("a fix that lints WORSE than the current RTL is rejected — original ships", async () => {
    runCli.mockImplementation(lintByContent);
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))                          // initial review
      .mockResolvedValueOnce(llmReply({ code: LINT_REGRESSION, fixes: ["broke it"] })); // fix

    const d = await rtlReviewNode(state());

    expect(d.rtl_generate.code).toBe(CLEAN);                    // never adopted
    expect(d.rtl_review._iterations.some((i) => i.rejected)).toBe(true);
    expect(callLLM).toHaveBeenCalledTimes(2);                   // no wasted re-review
    // Gate linted both candidate and current
    expect(runCli.mock.calls.length).toBe(2);
  });

  it("a fix that lints clean is adopted — with the full quality steps applied", async () => {
    runCli.mockImplementation(lintByContent);
    const fixWithLeak = CLEAN.replace("q <= '0;", "q <= '0; // fixed")
      + "\n\nmodule ctr_tb;\n  initial $finish;\nendmodule";    // embedded TB leak
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))
      .mockResolvedValueOnce(llmReply({ code: fixWithLeak, fixes: ["patched reset"] }))
      .mockResolvedValueOnce(llmReply(PASS));                   // re-review

    const d = await rtlReviewNode(state());

    expect(d.rtl_generate.code).toContain("// fixed");          // adopted
    expect(d.rtl_generate.code).not.toContain("module ctr_tb"); // embedded TB stripped
    expect(d.rtl_review.verdict).toBe("PASS");
  });

  it("no backend configured → gate abstains, fix adopted as before", async () => {
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))
      .mockResolvedValueOnce(llmReply({ code: CLEAN + "\n// touched", fixes: ["x"] }))
      .mockResolvedValueOnce(llmReply(PASS));

    const d = await rtlReviewNode(state({ backendUrl: "" }));

    expect(d.rtl_generate.code).toContain("// touched");
    expect(runCli).not.toHaveBeenCalled();
  });

  it("CLI failure → gate abstains rather than blocking the pipeline", async () => {
    runCli.mockResolvedValue({ _error: true, _msg: "backend down" });
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))
      .mockResolvedValueOnce(llmReply({ code: CLEAN + "\n// touched", fixes: ["x"] }))
      .mockResolvedValueOnce(llmReply(PASS));

    const d = await rtlReviewNode(state());

    expect(d.rtl_generate.code).toContain("// touched");
  });
});
