// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Riadh Ben Abdelhamid

// Review-fix quality bar (user directive after nemotron run 7): a fix
// generated by RTL Review is generated RTL, and gets the SAME quality steps
// as rtl_generate output — echo-strip, embedded-TB strip + deterministic
// repair, and a LINT GATE that rejects a candidate compiling worse than the
// code it replaces. (Measured: a review fix rewrote a clean reset to
// 'q <= (DATA_W){1'b0}' and appended a _tb module; the lint stage's LLM then
// couldn't recover in 2 iterations.)

import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../src/llm/index.js", async function() {
  const actual = await vi.importActual("../src/llm/extractJSON.js");
  return { callLLM: vi.fn(), extractJSON: actual.extractJSON, addRetryHint: function(s) { return s; } };
});
vi.mock("../src/cli/index.js", function() {
  return {
    extractInfoEvidence: function() { return []; },
    attachInfoEvidence: function(t) { return t; },
    runCli: vi.fn(),
    // Parses BOTH severities. It used to hardcode `warnings: []`, which made
    // the run-38 semantic-warning gate untestable here — the stub silently
    // discarded exactly the signal under test.
    parseCLIOutput: function(stderr) {
      const all = String(stderr || "").split("\n");
      const errors = all.filter(function(l) { return l.indexOf("%Error") === 0; })
        .map(function(l) { return { code: "SYNTAX", sev: "error", msg: l }; });
      const warnings = all.filter(function(l) { return l.indexOf("%Warning-") === 0; })
        .map(function(l) {
          const m = l.match(/^%Warning-(\w+)/);
          return { code: m ? m[1] : "UNKNOWN", sev: "warning", msg: l };
        });
      return { errors: errors, warnings: warnings };
    },
    parseTestLine: function() { return null; },
    parseCoverageDat: function() { return { line: 90, branch: 80, toggle: 70 }; },
    CliBackendError: class extends Error {},
  };
});

const { rtlReviewNode } = await import("../src/pipeline/nodes/rtl_review.js");
const { callLLM } = await import("../src/llm/index.js");
const { runCli } = await import("../src/cli/index.js");

const CLEAN = [
  "`timescale 1ns/1ps",
  "module ctr(input logic clk, input logic rst_n, input logic en, output logic [3:0] q);",
  "  always_ff @(posedge clk or negedge rst_n) begin",
  "    if (!rst_n) q <= '0;",
  "    else if (en) q <= q + 1'b1;",
  "  end",
  "endmodule",
].join("\n");

// The measured run-7 degradation: malformed replication. The deterministic
// paren-replication transform repairs THIS form, so to test the lint gate we
// use a regression the transforms cannot fix (an unclosed begin).
const LINT_REGRESSION = CLEAN.replace("q <= q + 1'b1;", "q <= q + 1'b1; begin");

function state(cfg) {
  return {
    elicit: { modName: "ctr" },
    spec: { modName: "ctr", requirements: [], iface: [], params: [] },
    architect: { strategy: "single" },
    rtl_generate: { code: CLEAN },
    _config: Object.assign({
      provider: "openai", model: "gpt-4o", apiKey: "sk-test",
      maxRtlReviewIters: 2, syntaxRepair: true,
      backendUrl: "http://localhost:3001", strictCli: false,
      cliRetryCount: 0, backendTimeoutSec: 10, stageSettings: {},
    }, cfg || {}),
    _onLog: null, _signal: null,
    // no _services → legacy inline path (chain unavailable)
  };
}

const llmReply = (json) => ({
  text: JSON.stringify(json), tokensIn: 10, tokensOut: 5, latencyMs: 1,
  model: "gpt-4o", provider: "openai", stopReason: "stop",
});
const NEEDS_FIX = { verdict: "NEEDS_FIX", score: 40, issues: [
  { id: "RR-001", severity: "major", category: "correctness", line: 4, description: "x", fix: "y" },
] };
const PASS = { verdict: "PASS", score: 90, issues: [] };

// runCli mock: lint result depends on the candidate's content.
function lintByContent(url, payload) {
  const code = Object.values(payload.files)[0];
  const bad = code.indexOf("1'b1; begin") >= 0;   // the injected unclosed begin
  return Promise.resolve({ stdout: "", stderr: bad ? "%Error: syntax error, unexpected end\n" : "", exitCode: bad ? 1 : 0 });
}

beforeEach(() => { callLLM.mockReset(); runCli.mockReset(); });

describe("review-fix lint gate (legacy inline path)", () => {
  it("a fix that lints WORSE than the current RTL is rejected — original ships", async () => {
    runCli.mockImplementation(lintByContent);
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))                          // initial review
      .mockResolvedValue(llmReply({ code: LINT_REGRESSION, fixes: ["broke it"] })); // every fix regresses

    const d = await rtlReviewNode(state());

    expect(d.rtl_generate.code).toBe(CLEAN);                    // never adopted
    expect(d.rtl_review._iterations.some((i) => i.rejected)).toBe(true);
    // A rejection is NOT a no-op (run 39): the loop RETRIES to the cap rather
    // than ending, but it never wastes a re-review on code it kept unchanged.
    // maxRtlReviewIters 2 → 1 review + 2 fix attempts.
    expect(callLLM).toHaveBeenCalledTimes(3);
    const reviewCalls = callLLM.mock.calls.filter(function(c) {
      return /Review the/.test(String(c[0] && c[0].userMessage));
    });
    expect(reviewCalls.length).toBe(1);                          // no re-review of unchanged code
    expect(d.rtl_review._iterations.every(function(i) {
      return !i._structured || !i._structured.fixOutcome
        || i._structured.fixOutcome !== "identical";
    })).toBe(true);                                              // recorded as rejected, not no-op
  });

  it("a fix that lints clean is adopted — with the full quality steps applied", async () => {
    runCli.mockImplementation(lintByContent);
    const fixWithLeak = CLEAN.replace("q <= '0;", "q <= '0; // fixed")
      + "\n\nmodule ctr_tb;\n  initial $finish;\nendmodule";    // embedded TB leak
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))
      .mockResolvedValueOnce(llmReply({ code: fixWithLeak, fixes: ["patched reset"] }))
      .mockResolvedValueOnce(llmReply(PASS));                   // re-review

    const d = await rtlReviewNode(state());

    expect(d.rtl_generate.code).toContain("// fixed");          // adopted
    expect(d.rtl_generate.code).not.toContain("module ctr_tb"); // embedded TB stripped
    expect(d.rtl_review.verdict).toBe("PASS");
  });

  it("no backend configured → gate abstains, fix adopted as before", async () => {
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))
      .mockResolvedValueOnce(llmReply({ code: CLEAN + "\n// touched", fixes: ["x"] }))
      .mockResolvedValueOnce(llmReply(PASS));

    const d = await rtlReviewNode(state({ backendUrl: "" }));

    expect(d.rtl_generate.code).toContain("// touched");
    expect(runCli).not.toHaveBeenCalled();
  });

  it("CLI failure → gate abstains rather than blocking the pipeline", async () => {
    runCli.mockResolvedValue({ _error: true, _msg: "backend down" });
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))
      .mockResolvedValueOnce(llmReply({ code: CLEAN + "\n// touched", fixes: ["x"] }))
      .mockResolvedValueOnce(llmReply(PASS));

    const d = await rtlReviewNode(state());

    expect(d.rtl_generate.code).toContain("// touched");
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// Semantic-warning monotonicity (measured: run 38). The gate counted ERRORS
// only, so a review fix raised MULTIDRIVEN from 5 to 7 unchallenged: `busy`,
// `done`, `bit_cnt` and `start_sampled` ended up written from three different
// always_ff blocks, 8 of that run's 14 test failures landed on exactly those
// signals, and yosys refused to build a model. Neither existing guard saw it —
// the score gate correctly read crit+major 3 → 2, the error-count gate
// correctly read 1 → 0 — because MULTIDRIVEN is a warning.
// ═══════════════════════════════════════════════════════════════════════════
describe("review-fix semantic-warning gate (run 38)", () => {
  // The candidate adds a second always_ff driving `q`, exactly run 38's shape.
  const MULTIDRIVEN_REGRESSION = CLEAN.replace(
    "endmodule",
    "  always_ff @(posedge clk) if (en) q <= '1;\nendmodule");

  // Lint mock: MULTIDRIVEN count follows the number of always_ff blocks
  // writing q. Errors stay at zero — the point is that a WARNING regressed.
  function lintWarnByContent(url, payload) {
    const code = Object.values(payload.files)[0];
    const drivers = (code.match(/q <= /g) || []).length;
    const warns = Array.from({ length: Math.max(drivers - 1, 0) }, (_, i) =>
      "%Warning-MULTIDRIVEN: ctr.sv:" + (10 + i) + ":5: Variable written to in always_ff also written by other process\n").join("");
    return Promise.resolve({ stdout: "", stderr: warns, exitCode: 0 });
  }

  it("a fix that adds bug-hiding warnings is rejected, though it has 0 errors", async () => {
    runCli.mockImplementation(lintWarnByContent);
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))
      .mockResolvedValue(llmReply({ code: MULTIDRIVEN_REGRESSION, fixes: ["added a driver"] }));

    const d = await rtlReviewNode(state());

    expect(d.rtl_generate.code).toBe(CLEAN);                     // never adopted
    expect(d.rtl_generate.code).not.toContain("q <= '1;");
    expect(callLLM).toHaveBeenCalledTimes(3);                    // retried to the cap, not ended
    const rejected = d.rtl_review._iterations.filter(function(i) {
      return i._structured && /^rejected:/.test(i._structured.fixOutcome || "");
    });
    expect(rejected.length).toBeGreaterThan(0);
    expect(rejected[0]._structured.fixOutcome).toBe("rejected:semantic");
  });

  it("HYGIENE warnings do NOT block a fix — only bug-hiding ones do", async () => {
    runCli.mockImplementation((url, payload) => {
      const code = Object.values(payload.files)[0];
      const n = code.indexOf("// touched") >= 0 ? 6 : 0;
      return Promise.resolve({ stdout: "", exitCode: 0,
        stderr: Array.from({ length: n }, (_, i) =>
          "%Warning-UNUSEDSIGNAL: ctr.sv:" + (i + 3) + ":5: Signal is not used\n").join("") });
    });
    callLLM
      .mockResolvedValueOnce(llmReply(NEEDS_FIX))
      .mockResolvedValueOnce(llmReply({ code: CLEAN + "\n// touched", fixes: ["x"] }))
      .mockResolvedValueOnce(llmReply(PASS));

    const d = await rtlReviewNode(state());

    expect(d.rtl_generate.code).toContain("// touched");          // adopted despite +6 warnings
  });

  it("the compile-honesty gate still reads errors after the counts refactor", async () => {
    // A PASS verdict on code the compiler rejects must be downgraded — this is
    // the call site that broke when lintErrorCount became lintCountsOf.
    runCli.mockImplementation(() => Promise.resolve({
      stdout: "", exitCode: 1,
      stderr: "%Error: ctr.sv:4:5: syntax error, unexpected end\n",
    }));
    callLLM.mockResolvedValueOnce(llmReply(PASS));

    const d = await rtlReviewNode(state());

    expect(d.rtl_review.verdict).toBe("NEEDS_FIX");
    expect(d.rtl_review._compileErrors).toBe(1);
  });
});
